---
secrets:
  dockerhub_password:
    path: secret/dockerhub/password
  gcm_api_key:
    path: secret/keys/gcm
  teamwire_db_password:
    path: secret/database/password
  aes_key:
    path: secret/database/aes_key
  mysql_root_password:
    path: secret/dbserver/mysql_root_password
  clustercheck_password:
    path: secret/dbserver/clustercheck_password
  xtrabackup_password:
    path: secret/dbserver/xtrabackup_password
  redis_pass:
    path: secret/redis/password
  smtp_smartpass:
    path: secret/smtp/password
  monitoring_db_password:
    path: secret/monitoring/db_password
  monitoring_db_web_password:
    path: secret/monitoring/db_web_password
  icinga_admin_password:
    path: secret/monitoring/icinga_admin_password
  icinga_salt:
    path: secret/monitoring/icinga_salt
  icinga_api_password:
    path: secret/monitoring/icinga_api_password
  reportfile_password:
    path: secret/reportfile/password
  voip_jvb_password:
    path: secret/voip/jvb_password
  voip_jicofo_password:
    path: secret/voip/jicofo_password
  voip_jibri_password:
    path: secret/voip/jibri_password
  voip_stun_password:
    path: secret/voip/stun_password
  jwt_app_secret:
    path: secret/voip/jwt_app_secret
vault_certificate_ttl: 17532h
